---
app:
  id: read-only
  name: Read Only Service
  log-level: trace

grpc:
  ip: 0.0.0.0
  port: 30001

postgresql:
  host: 0.0.0.0
  port: "5436"
  username: reader
  database: reader
  password: postgres
